### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by meriadec** [AstroquirksHQ/astroquirks-front#14]
![Image](https://user-images.githubusercontent.com/2527857/212491289-7350b487-1a95-4ff2-a49a-c1f5b4c264d1.png)

**Comment by meriadec** [comment]
It's probably a bug yes 🤔 
but as https://github.com/AstroquirksHQ/astroquirks-front/issues/8 I've just been deployed, can you check if you still repro?

thx Oleksandra

**Comment by meriadec** [comment]
hard to reproduce, please re-open if you have a straight reproducible scenario

**Comment by malikfassi** [comment]
Bug still exists, but i can't manage to reproduce it consistently

**Comment by meriadec** [comment]
let's wait for our thousands of users to complain then will fix
